# This migration has been generated by the command:
# rails generate migration add_description_to_articles

# The purpose of this migration is to add Description, Created at and Updated at columns to Articles Table
class AddDescriptionToArticles < ActiveRecord::Migration[5.2]
  # We define whatever changes we want to make in the schema inside the change method.
  def change
    # add_column is a rails method to add column to a table. Default param is optional.
    # add_column :table_name, :column_name, :data_type_of_column, :default => 'default value'
    add_column :articles, :description, :text
    add_column :articles, :created_at, :datetime
    add_column :articles, :updated_at, :datetime
  end
end
